export const countrycode =[
    // {text:"中国","en":"China",value:"+86",lang:'zh'},
    // {text:"中国香港","en":"Hong Kong (SAR)",value:"+852"},
    // {text:"中国澳门","en":"Macao",value:"+853"},
    // {text:"中国台湾","en":"Taiwan",value:"+886"},
    // {text:"美国","en":"United States",value:"+1",lang:'en'},
    {text:"新加坡","en":"Singapore",value:"+65"},
    {text:"马来西亚","en":"Malaysia",value:"+60"},
    {text:"柬埔寨","en":"Cambodia",value:"+855"},
    {text:"菲律宾","en":"Philippines",value:"+63"},
    {text:"缅甸","en":"Burma",value:"+95"},
    {text:"越南","en":"Vietnam",value:"+84",lang:'ind'},
    // {text:"阿拉伯联合酋长国","en":"United Arab Emirates",value:"+971"},
]
export const allCode =[{text:"中国","en":"China",value:"+86",lang:'zh'},
{text:"中国香港","en":"Hong Kong (SAR)",value:"+852"},
{text:"中国澳门","en":"Macao",value:"+853"},
{text:"中国台湾","en":"Taiwan",value:"+886"},
{text:"美国","en":"United States",value:"+1",lang:'en'},
{text:"新加坡","en":"Singapore",value:"+65"},
{text:"马来西亚","en":"Malaysia",value:"+60"},
{text:"柬埔寨","en":"Cambodia",value:"+855"},
{text:"菲律宾","en":"Philippines",value:"+63"},
{text:"缅甸","en":"Burma",value:"+95"},
{text:"越南","en":"Vietnam",value:"+84",lang:'ind'},
{text:"日本","en":"Japan",value:"+81"},
{text:"老挝","en":"Laos",value:"+856"},
{text:"澳大利亚","en":"Australia",value:"+61"},
{text:"德国","en":"Germany",value:"+49"},
{text:"法国","en":"France",value:"+33"},
{text:"加拿大","en":"Canada",value:"+1"},
{text:"阿富汗","en":"Afghanistan",value:"+93"},
{text:"阿尔巴尼亚","en":"Albania",value:"+355"},
{text:"阿尔及利亚","en":"Algeria",value:"+213"},
{text:"美属萨摩亚","en":"American Samoa",value:"+684"},
{text:"安道尔","en":"Andorra",value:"+376"},
{text:"安哥拉","en":"Angola",value:"+244"},
{text:"安圭拉","en":"Anguilla",value:"+1264"},
{text:"南极洲","en":"Antarctica",value:"+672"},
{text:"安提瓜和巴布达","en":"Antigua and Barbuda",value:"+1268"},
{text:"阿根廷","en":"Argentina",value:"+54"},
{text:"亚美尼亚","en":"Armenia",value:"+374"},
{text:"阿鲁巴","en":"Aruba",value:"+297"},
{text:"奥地利","en":"Austria",value:"+43"},
{text:"阿塞拜疆","en":"Azerbaijan",value:"+994"},
{text:"巴林","en":"Bahrain",value:"+973"},
{text:"孟加拉国","en":"Bangladesh",value:"+880"},
{text:"巴巴多斯","en":"Barbados",value:"+1246"},
{text:"白俄罗斯","en":"Belarus",value:"+375"},
{text:"比利时","en":"Belgium",value:"+32"},
{text:"伯利兹","en":"Belize",value:"+501"},
{text:"贝宁","en":"Benin",value:"+229"},
{text:"百慕大","en":"Bermuda",value:"+1441"},
{text:"不丹","en":"Bhutan",value:"+975"},
{text:"玻利维亚","en":"Bolivia",value:"+591"},
{text:"波黑","en":"Bosnia and Herzegovina",value:"+387"},
{text:"博茨瓦纳","en":"Botswana",value:"+267"},
{text:"巴西","en":"Brazil",value:"+55"},
{text:"英属维尔京群岛","en":"British Virgin Islands",value:"+1284"},
{text:"文莱","en":"Brunei Darussalam",value:"+673"},
{text:"保加利亚","en":"Bulgaria",value:"+359"},
{text:"布基纳法索","en":"Burkina Faso",value:"+226"},
{text:"布隆迪","en":"Burundi",value:"+257"},
{text:"喀麦隆","en":"Cameroon",value:"+237"},
{text:"佛得角","en":"Cape Verde",value:"+238"},
{text:"开曼群岛","en":"Cayman Islands",value:"+1345"},
{text:"中非","en":"Central African Republic",value:"+236"},
{text:"乍得","en":"Chad",value:"+235"},
{text:"智利","en":"Chile",value:"+56"},
{text:"圣诞岛","en":"Christmas Island",value:"+61"},
{text:"科科斯（基林）群岛","en":"Cocos (Keeling) Islands",value:"+61"},
{text:"哥伦比亚","en":"Colombia",value:"+57"},
{text:"科摩罗","en":"Comoros",value:"+269"},
{text:"刚果（金）","en":"Democratic Republic of the Congo",value:"+243"},
{text:"刚果（布）","en":"Republic of the Congo",value:"+242"},
{text:"库克群岛","en":"Cook Islands",value:"+682"},
{text:"哥斯达黎加","en":"Costa Rica",value:"+506"},
{text:"科特迪瓦","en":"Cote d'Ivoire",value:"+225"},
{text:"克罗地亚","en":"Croatia",value:"+385"},
{text:"古巴","en":"Cuba",value:"+53"},
{text:"塞浦路斯","en":"Cyprus",value:"+357"},
{text:"捷克","en":"Czech Republic",value:"+420"},
{text:"丹麦","en":"Denmark",value:"+45"},
{text:"吉布提","en":"Djibouti",value:"+253"},
{text:"多米尼克","en":"Dominica",value:"+1767"},
{text:"多米尼加","en":"Dominican Republic",value:"+1809"},
{text:"厄瓜多尔","en":"Ecuador",value:"+593"},
{text:"埃及","en":"Egypt",value:"+20"},
{text:"萨尔瓦多","en":"El Salvador",value:"+503"},
{text:"赤道几内亚","en":"Equatorial Guinea",value:"+240"},
{text:"厄立特里亚","en":"Eritrea",value:"+291"},
{text:"爱沙尼亚","en":"Estonia",value:"+372"},
{text:"埃塞俄比亚","en":"Ethiopia",value:"+251"},
{text:"福克兰群岛（马尔维纳斯）","en":"Falkland Islands (Islas Malvinas)",value:"+500"},
{text:"法罗群岛","en":"Faroe Islands",value:"+298"},
{text:"斐济","en":"Fiji",value:"+679"},
{text:"芬兰","en":"Finland",value:"+358"},
{text:"法属圭亚那","en":"French Guiana",value:"+594"},
{text:"法属波利尼西亚","en":"French Polynesia",value:"+689"},
{text:"加蓬","en":"Gabon",value:"+241"},
{text:"格鲁吉亚","en":"Georgia",value:"+995"},
{text:"加纳","en":"Ghana",value:"+233"},
{text:"直布罗陀","en":"Gibraltar",value:"+350"},
{text:"希腊","en":"Greece",value:"+30"},
{text:"格陵兰","en":"Greenland",value:"+299"},
{text:"格林纳达","en":"Grenada",value:"+1473"},
{text:"瓜德罗普","en":"Guadeloupe",value:"+590"},
{text:"关岛","en":"Guam",value:"+1671"},
{text:"危地马拉","en":"Guatemala",value:"+502"},
{text:"根西岛","en":"Guernsey",value:"+1481"},
{text:"几内亚","en":"Guinea",value:"+224"},
{text:"几内亚比绍","en":"Guinea-Bissau",value:"+245"},
{text:"圭亚那","en":"Guyana",value:"+592"},
{text:"海地","en":"Haiti",value:"+509"},
{text:"梵蒂冈","en":"Holy See (Vatican City)",value:"+379"},
{text:"洪都拉斯","en":"Honduras",value:"+504"},
{text:"匈牙利","en":"Hungary",value:"+36"},
{text:"冰岛","en":"Iceland",value:"+354"},
{text:"印度","en":"India",value:"+91"},
{text:"印度尼西亚","en":"Indonesia",value:"+62"},
{text:"伊朗","en":"Iran",value:"+98"},
{text:"伊拉克","en":"Iraq",value:"+964"},
{text:"爱尔兰","en":"Ireland",value:"+353"},
{text:"以色列","en":"Israel",value:"+972"},
{text:"意大利","en":"Italy",value:"+39"},
{text:"牙买加","en":"Jamaica",value:"+1876"},
{text:"约旦","en":"Jordan",value:"+962"},
{text:"哈萨克斯坦","en":"Kazakhstan",value:"+73"},
{text:"肯尼亚","en":"Kenya",value:"+254"},
{text:"基里巴斯","en":"Kiribati",value:"+686"},
{text:"朝鲜","en":"North Korea",value:"+850"},
{text:"韩国","en":"South Korea",value:"+82"},
{text:"科威特","en":"Kuwait",value:"+965"},
{text:"吉尔吉斯斯坦","en":"Kyrgyzstan",value:"+996"},
{text:"拉脱维亚","en":"Latvia",value:"+371"},
{text:"黎巴嫩","en":"Lebanon",value:"+961"},
{text:"莱索托","en":"Lesotho",value:"+266"},
{text:"利比里亚","en":"Liberia",value:"+231"},
{text:"利比亚","en":"Libya",value:"+218"},
{text:"列支敦士登","en":"Liechtenstein",value:"+423"},
{text:"立陶宛","en":"Lithuania",value:"+370"},
{text:"卢森堡","en":"Luxembourg",value:"+352"},
{text:"前南马其顿","en":"The Former Yugoslav Republic of Macedonia",value:"+389"},
{text:"马达加斯加","en":"Madagascar",value:"+261"},
{text:"马拉维","en":"Malawi",value:"+265"},
{text:"马尔代夫","en":"Maldives",value:"+960"},
{text:"马里","en":"Mali",value:"+223"},
{text:"马耳他","en":"Malta",value:"+356"},
{text:"马绍尔群岛","en":"Marshall Islands",value:"+692"},
{text:"马提尼克","en":"Martinique",value:"+596"},
{text:"毛里塔尼亚","en":"Mauritania",value:"+222"},
{text:"毛里求斯","en":"Mauritius",value:"+230"},
{text:"马约特","en":"Mayotte",value:"+269"},
{text:"墨西哥","en":"Mexico",value:"+52"},
{text:"密克罗尼西亚","en":"Federated States of Micronesia",value:"+691"},
{text:"摩尔多瓦","en":"Moldova",value:"+373"},
{text:"摩纳哥","en":"Monaco",value:"+377"},
{text:"蒙古","en":"Mongolia",value:"+976"},
{text:"蒙特塞拉特","en":"Montserrat",value:"+1664"},
{text:"摩洛哥","en":"Morocco",value:"+212"},
{text:"莫桑比克","en":"Mozambique",value:"+258"},
{text:"纳米尼亚","en":"Namibia",value:"+264"},
{text:"瑙鲁","en":"Nauru",value:"+674"},
{text:"尼泊尔","en":"Nepal",value:"+977"},
{text:"荷兰","en":"Netherlands",value:"+31"},
{text:"荷属安的列斯","en":"Netherlands Antilles",value:"+599"},
{text:"新喀里多尼亚","en":"New Caledonia",value:"+687"},
{text:"新西兰","en":"New Zealand",value:"+64"},
{text:"尼加拉瓜","en":"Nicaragua",value:"+505"},
{text:"尼日尔","en":"Niger",value:"+227"},
{text:"尼日利亚","en":"Nigeria",value:"+234"},
{text:"纽埃","en":"Niue",value:"+683"},
{text:"诺福克岛","en":"Norfolk Island",value:"+6723"},
{text:"北马里亚纳","en":"Northern Mariana Islands",value:"+1"},
{text:"挪威","en":"Norway",value:"+47"},
{text:"阿曼","en":"Oman",value:"+968"},
{text:"巴基斯坦","en":"Pakistan",value:"+92"},
{text:"帕劳","en":"Palau",value:"+680"},
{text:"巴拿马","en":"Panama",value:"+507"},
{text:"巴布亚新几内亚","en":"Papua New Guinea",value:"+675"},
{text:"巴拉圭","en":"Paraguay",value:"+595"},
{text:"秘鲁","en":"Peru",value:"+51"},
{text:"波兰","en":"Poland",value:"+48"},
{text:"葡萄牙","en":"Portugal",value:"+351"},
{text:"波多黎各","en":"Puerto Rico",value:"+1809"},
{text:"卡塔尔","en":"Qatar",value:"+974"},
{text:"留尼汪","en":"Reunion",value:"+262"},
{text:"罗马尼亚","en":"Romania",value:"+40"},
{text:"俄罗斯","en":"Russia",value:"+7"},
{text:"卢旺达","en":"Rwanda",value:"+250"},
{text:"圣赫勒拿","en":"Saint Helena",value:"+290"},
{text:"圣基茨和尼维斯","en":"Saint Kitts and Nevis",value:"+1869"},
{text:"圣卢西亚","en":"Saint Lucia",value:"+1758"},
{text:"圣皮埃尔和密克隆","en":"Saint Pierre and Miquelon",value:"+508"},
{text:"圣文森特和格林纳丁斯","en":"Saint Vincent and the Grenadines",value:"+1784"},
{text:"萨摩亚","en":"Samoa",value:"+685"},
{text:"圣马力诺","en":"San Marino",value:"+378"},
{text:"圣多美和普林西比","en":"Sao Tome and Principe",value:"+239"},
{text:"沙特阿拉伯","en":"Saudi Arabia",value:"+966"},
{text:"塞内加尔","en":"Senegal",value:"+221"},
{text:"塞尔维亚和黑山","en":"Serbia and Montenegro",value:"+381"},
{text:"塞舌尔","en":"Seychelles",value:"+248"},
{text:"塞拉利","en":"Sierra Leone",value:"+232"},
{text:"斯洛伐克","en":"Slovakia",value:"+421"},
{text:"斯洛文尼亚","en":"Slovenia",value:"+386"},
{text:"所罗门群岛","en":"Solomon Islands",value:"+677"},
{text:"索马里","en":"Somalia",value:"+252"},
{text:"南非","en":"South Africa",value:"+27"},
{text:"西班牙","en":"Spain",value:"+34"},
{text:"斯里兰卡","en":"Sri Lanka",value:"+94"},
{text:"苏丹","en":"Sudan",value:"+249"},
{text:"苏里南","en":"Suriname",value:"+597"},
{text:"斯瓦尔巴岛和扬马延岛","en":"Svalbard",value:"+47"},
{text:"斯威士兰","en":"Swaziland",value:"+268"},
{text:"瑞典","en":"Sweden",value:"+46"},
{text:"瑞士","en":"Switzerland",value:"+41"},
{text:"叙利亚","en":"Syria",value:"+963"},
{text:"塔吉克斯坦","en":"Tajikistan",value:"+992"},
{text:"坦桑尼亚","en":"Tanzania",value:"+255"},
{text:"泰国","en":"Thailand",value:"+66"},
{text:"巴哈马","en":"The Bahamas",value:"+1242"},
{text:"冈比亚","en":"The Gambia",value:"+220"},
{text:"多哥","en":"Togo",value:"+228"},
{text:"托克劳","en":"Tokelau",value:"+690"},
{text:"汤加","en":"Tonga",value:"+676"},
{text:"特立尼达和多巴哥","en":"Trinidad and Tobago",value:"+1868"},
{text:"突尼斯","en":"Tunisia",value:"+216"},
{text:"土耳其","en":"Turkey",value:"+90"},
{text:"土库曼斯坦","en":"Turkmenistan",value:"+993"},
{text:"特克斯和凯科斯群岛","en":"Turks and Caicos Islands",value:"+1649"},
{text:"图瓦卢","en":"Tuvalu",value:"+688"},
{text:"乌干达","en":"Uganda",value:"+256"},
{text:"乌克兰","en":"Ukraine",value:"+380"},
{text:"阿拉伯联合酋长国","en":"United Arab Emirates",value:"+971"},
{text:"英国","en":"United Kingdom",value:"+44"},
{text:"乌拉圭","en":"Uruguay",value:"+598"},
{text:"乌兹别克斯坦","en":"Uzbekistan",value:"+998"},
{text:"瓦努阿图","en":"Vanuatu",value:"+678"},
{text:"委内瑞拉","en":"Venezuela",value:"+58"},
{text:"美属维尔京群岛","en":"Virgin Islands",value:"+1340"},
{text:"瓦利斯和富图纳","en":"Wallis and Futuna",value:"+681"},
{text:"也门","en":"Yemen",value:"+967"},
{text:"赞比亚","en":"Zambia",value:"+260"},
{text:"津巴布韦","en":"Zimbabwe",value:"+263"}]
